apiVersion: v1
kind: Service
metadata:
  name: pod-a-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pod-a
spec:
  selector:
    app: pod-a
  ports:
    - name: inbound
      port: {{ .Values.podA.service.port }}
      targetPort: {{ .Values.envoy.ports.inbound }}
      protocol: TCP
  type: ClusterIP
