{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespaces.gateway }}
  labels:
    app: {{ .Values.gateway.name }}
spec:
  selector:
    app: {{ .Values.gateway.name }}
  ports:
    - name: egress
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.ports.listen }}
      protocol: TCP
  type: ClusterIP
{{- end }}
