apiVersion: v1
kind: Service
metadata:
  name: pod-b-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pod-b
spec:
  selector:
    app: pod-b
  ports:
    - name: inbound
      port: {{ .Values.podB.service.port }}
      targetPort: {{ .Values.envoy.ports.inbound }}
      protocol: TCP
  type: ClusterIP
